import { deepFreeze } from "./utils.js";

export const EPIC_C_RAW_ITEMS = deepFreeze([
  {
    id: "wiki-morocco-overview",
    sourceId: "wikipedia",
    sourceItemId: "Morocco",
    sourceUrl: "https://en.wikipedia.org/wiki/Morocco",
    canonicalUrl: "https://openscroll.app/item/wikipedia/morocco",
    type: "article",
    title: "Morocco overview",
    originalTitle: "Morocco",
    description: "A broad encyclopedia entry for Morocco, including geography, history, languages, and culture.",
    creators: [{ name: "Wikipedia contributors", role: "author" }],
    publishedAt: "2026-08-01T00:00:00.000Z",
    temporalCoverage: "historic and contemporary",
    places: [{ label: "Morocco", countryCode: "MA", coordinates: [31.7917, -7.0926] }],
    languages: ["en", "ar", "fr"],
    topics: ["History", "Culture"],
    entities: [{ id: "Q1028", label: "Morocco", source: "wikidata" }],
    collection: "Wikipedia articles",
    media: { kind: "text", url: "https://en.wikipedia.org/wiki/Morocco", accessibility: { altText: "Text article about Morocco" } },
    rights: { licenseId: "cc-by-sa-4.0", sourceVerified: true, attribution: "Wikipedia contributors" }
  },
  {
    id: "wikidata-gnawa",
    sourceId: "wikidata",
    sourceItemId: "Q1501622",
    sourceUrl: "https://www.wikidata.org/wiki/Q1501622",
    canonicalUrl: "https://openscroll.app/item/wikidata/gnawa",
    type: "knowledge-entity",
    title: "Gnawa",
    description: "Knowledge graph entity connecting Gnawa music, communities, places, and related cultural concepts.",
    creators: [{ name: "Wikidata contributors", role: "curator" }],
    places: [{ label: "Morocco", countryCode: "MA" }],
    languages: ["multilingual"],
    topics: ["Music", "Culture"],
    entities: [{ id: "Q1501622", label: "Gnawa", source: "wikidata" }],
    collection: "Wikidata entities",
    media: { kind: "knowledge-entity", url: "https://www.wikidata.org/wiki/Q1501622" },
    rights: { licenseId: "cc0", sourceVerified: true, attribution: "Wikidata contributors" }
  },
  {
    id: "wiktionary-darija",
    sourceId: "wiktionary",
    sourceItemId: "Moroccan Arabic",
    sourceUrl: "https://en.wiktionary.org/wiki/Moroccan_Arabic",
    canonicalUrl: "https://openscroll.app/item/wiktionary/darija",
    type: "dictionary",
    title: "Darija, written and spoken",
    originalTitle: "الدارجة، مكتوبة ومنطوقة",
    description: "Dictionary and language material for Moroccan Arabic with script and pronunciation context.",
    creators: [{ name: "Wiktionary contributors", role: "author" }],
    places: [{ label: "Morocco", countryCode: "MA" }],
    languages: ["en", "ary", "ar"],
    topics: ["Darija", "Culture"],
    entities: [{ id: "Q56426", label: "Moroccan Arabic", source: "wikidata" }],
    collection: "Wiktionary entries",
    media: { kind: "text", url: "https://en.wiktionary.org/wiki/Moroccan_Arabic", accessibility: { altText: "Dictionary entry for Moroccan Arabic" } },
    rights: { licenseId: "cc-by-sa-4.0", sourceVerified: true, attribution: "Wiktionary contributors" }
  },
  {
    id: "wikivoyage-medina-history",
    sourceId: "wikivoyage",
    sourceItemId: "Marrakesh",
    sourceUrl: "https://en.wikivoyage.org/wiki/Marrakesh",
    canonicalUrl: "https://openscroll.app/item/wikivoyage/marrakesh-medina",
    type: "travel-guide",
    title: "A brief history of the medina",
    originalTitle: "تاريخ موجز للمدينة العتيقة",
    description: "Open travel guide context for Marrakesh and its historic medina.",
    creators: [{ name: "Wikivoyage contributors", role: "author" }],
    places: [{ label: "Marrakesh", countryCode: "MA", coordinates: [31.6295, -7.9811] }],
    languages: ["en", "fr", "ar"],
    topics: ["History", "Architecture"],
    entities: [{ id: "Q101625", label: "Marrakesh", source: "wikidata" }],
    collection: "Wikivoyage guides",
    media: { kind: "text", url: "https://en.wikivoyage.org/wiki/Marrakesh", accessibility: { altText: "Travel guide text for Marrakesh" } },
    rights: { licenseId: "cc-by-sa-4.0", sourceVerified: true, attribution: "Wikivoyage contributors" }
  },
  {
    id: "wikisource-morocco-treaty",
    sourceId: "wikisource",
    sourceItemId: "Treaty of Peace and Friendship",
    sourceUrl: "https://en.wikisource.org/wiki/Treaty_of_Peace_and_Friendship_between_the_United_States_and_Morocco",
    canonicalUrl: "https://openscroll.app/item/wikisource/morocco-treaty",
    type: "source-text",
    title: "Treaty of Peace and Friendship",
    description: "A primary source text connected to Moroccan and United States diplomatic history.",
    creators: [{ name: "Wikisource contributors", role: "transcriber" }],
    publishedAt: "1787-07-18T00:00:00.000Z",
    temporalCoverage: "1787",
    places: [{ label: "Morocco", countryCode: "MA" }, { label: "United States", countryCode: "US" }],
    languages: ["en"],
    topics: ["History"],
    entities: [{ id: "Q1028", label: "Morocco", source: "wikidata" }],
    collection: "Wikisource diplomatic texts",
    media: { kind: "text", url: "https://en.wikisource.org/wiki/Treaty_of_Peace_and_Friendship_between_the_United_States_and_Morocco" },
    rights: { licenseId: "public-domain", sourceVerified: true, attribution: "Public domain source text via Wikisource" }
  },
  {
    id: "commons-gnawa-pulse",
    sourceId: "wikimedia-commons",
    sourceItemId: "File:Gnawa_music_Morocco.ogg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gnawa_music_Morocco.ogg",
    canonicalUrl: "https://openscroll.app/item/commons/gnawa-pulse",
    type: "audio",
    title: "The living pulse of Gnawa",
    originalTitle: "نبض كناوة الحي",
    description: "Eligible Commons audio representing Gnawa performance traditions.",
    creators: [{ name: "Wikimedia Commons contributor", role: "recordist" }],
    places: [{ label: "Essaouira", countryCode: "MA" }],
    languages: ["zgh", "ar", "en"],
    topics: ["Music", "Culture"],
    entities: [{ id: "Q1501622", label: "Gnawa", source: "wikidata" }],
    collection: "Wikimedia Commons files",
    media: { kind: "audio", url: "https://commons.wikimedia.org/wiki/File:Gnawa_music_Morocco.ogg", durationSeconds: 96, mimeType: "audio/ogg", accessibility: { transcript: "Instrumental or performance audio. Transcript pending source availability." } },
    rights: { licenseId: "cc-by-sa-4.0", sourceVerified: true, attribution: "Wikimedia Commons contributor" }
  },
  {
    id: "commons-hassan-tower-video",
    sourceId: "wikimedia-commons",
    sourceItemId: "File:Hassan_Tower_Rabat.webm",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hassan_Tower_Rabat.webm",
    canonicalUrl: "https://openscroll.app/item/commons/hassan-tower-video",
    type: "video",
    title: "Hassan Tower in motion",
    description: "Eligible Commons video material connected to Rabat architecture.",
    creators: [{ name: "Wikimedia Commons contributor", role: "videographer" }],
    places: [{ label: "Rabat", countryCode: "MA" }],
    languages: ["en", "ar"],
    topics: ["Architecture", "History"],
    entities: [{ id: "Q1135111", label: "Hassan Tower", source: "wikidata" }],
    collection: "Wikimedia Commons files",
    media: { kind: "video", url: "https://commons.wikimedia.org/wiki/File:Hassan_Tower_Rabat.webm", durationSeconds: 34, mimeType: "video/webm", accessibility: { captions: "Source captions required before autoplay or inline playback." } },
    rights: { licenseId: "cc-by-4.0", sourceVerified: true, attribution: "Wikimedia Commons contributor" }
  },
  {
    id: "openverse-ait-ben-haddou",
    sourceId: "openverse",
    sourceItemId: "openverse:ait-ben-haddou-ccby",
    sourceUrl: "https://openverse.org/image/example-ait-ben-haddou",
    canonicalUrl: "https://openscroll.app/item/openverse/ait-ben-haddou",
    originalSourceUrl: "https://example.org/photos/ait-ben-haddou",
    type: "image",
    title: "Ait Benhaddou earthen architecture",
    description: "Openverse candidate retained only after original-source license recheck.",
    creators: [{ name: "Original CC BY photographer", role: "photographer" }],
    places: [{ label: "Ait Benhaddou", countryCode: "MA" }],
    languages: ["en"],
    topics: ["Architecture", "Culture"],
    entities: [{ id: "Q194277", label: "Ait Benhaddou", source: "wikidata" }],
    collection: "Openverse images",
    media: { kind: "image", url: "https://example.org/photos/ait-ben-haddou.jpg", thumbnailUrl: "https://example.org/photos/ait-ben-haddou-thumb.jpg", width: 1600, height: 1067, mimeType: "image/jpeg", accessibility: { altText: "Earthen buildings at Ait Benhaddou in Morocco" } },
    rights: { licenseId: "cc-by-4.0", sourceVerified: true, attribution: "Original CC BY photographer" }
  },
  {
    id: "openverse-rejected-nc",
    sourceId: "openverse",
    sourceItemId: "openverse:morocco-nc",
    sourceUrl: "https://openverse.org/image/example-nc",
    originalSourceUrl: "https://example.org/restricted/morocco",
    type: "image",
    title: "Restricted Morocco image",
    description: "A candidate that must fail closed because the original source is noncommercial.",
    creators: [{ name: "Restricted photographer", role: "photographer" }],
    places: [{ label: "Morocco", countryCode: "MA" }],
    languages: ["en"],
    topics: ["Culture"],
    media: { kind: "image", url: "https://example.org/restricted/morocco.jpg" },
    rights: { licenseId: "cc-by-nc-4.0", sourceVerified: true, attribution: "Restricted photographer" }
  },
  {
    id: "openverse-review-unverified",
    sourceId: "openverse",
    sourceItemId: "openverse:morocco-unverified",
    sourceUrl: "https://openverse.org/image/example-unverified",
    originalSourceUrl: "https://example.org/unverified/morocco",
    type: "image",
    title: "Unverified Morocco image",
    description: "A candidate that looks open but must wait for source verification before entering the Scroll.",
    creators: [{ name: "Unverified photographer", role: "photographer" }],
    places: [{ label: "Morocco", countryCode: "MA" }],
    languages: ["en"],
    topics: ["Culture"],
    media: { kind: "image", url: "https://example.org/unverified/morocco.jpg", accessibility: { altText: "Unverified photo candidate from Morocco" } },
    rights: { licenseId: "cc-by-4.0", sourceVerified: false, attribution: "Unverified photographer" }
  },
  {
    id: "smithsonian-moroccan-robe",
    sourceId: "smithsonian-open-access",
    sourceItemId: "edanmdm:nmafa_robe_morocco",
    sourceUrl: "https://www.si.edu/object/example-moroccan-robe",
    canonicalUrl: "https://openscroll.app/item/smithsonian/moroccan-robe",
    type: "museum-object",
    title: "Moroccan robe in open access",
    description: "Museum object metadata and image normalized with institution and collection details.",
    creators: [{ name: "Unknown Moroccan maker", role: "maker" }],
    places: [{ label: "Morocco", countryCode: "MA" }],
    languages: ["en"],
    topics: ["Culture", "History"],
    entities: [{ id: "Q1028", label: "Morocco", source: "wikidata" }],
    collection: "Smithsonian National Museum of African Art",
    media: { kind: "image", url: "https://www.si.edu/openaccess/example-moroccan-robe.jpg", width: 1200, height: 1600, accessibility: { altText: "A Moroccan robe from the Smithsonian Open Access collection" } },
    rights: { licenseId: "cc0", sourceVerified: true, attribution: "Smithsonian Open Access" }
  },
  {
    id: "europeana-fez-postcard",
    sourceId: "europeana",
    sourceItemId: "europeana:fez-postcard",
    sourceUrl: "https://www.europeana.eu/item/example-fez-postcard",
    canonicalUrl: "https://openscroll.app/item/europeana/fez-postcard",
    type: "image",
    title: "Fez postcard",
    description: "Cultural aggregator record with provider, collection, and item-level public-domain statement.",
    creators: [{ name: "Holding institution", role: "provider" }],
    publishedAt: "1912-01-01T00:00:00.000Z",
    temporalCoverage: "early twentieth century",
    places: [{ label: "Fez", countryCode: "MA" }],
    languages: ["fr", "en"],
    topics: ["History", "Architecture"],
    collection: "Europeana postcards",
    media: { kind: "image", url: "https://example.org/europeana/fez-postcard.jpg", accessibility: { altText: "Historic postcard view of Fez" } },
    rights: { licenseId: "public-domain-mark", sourceVerified: true, attribution: "Europeana provider institution" }
  },
  {
    id: "dpla-morocco-map",
    sourceId: "dpla",
    sourceItemId: "dpla:morocco-map",
    sourceUrl: "https://dp.la/item/example-morocco-map",
    canonicalUrl: "https://openscroll.app/item/dpla/morocco-map",
    type: "map",
    title: "Historic map of Morocco",
    description: "DPLA map record with holding institution and open rights metadata.",
    creators: [{ name: "Library holding institution", role: "provider" }],
    publishedAt: "1900-01-01T00:00:00.000Z",
    temporalCoverage: "circa 1900",
    places: [{ label: "Morocco", countryCode: "MA" }],
    languages: ["en"],
    topics: ["History", "Open data"],
    collection: "DPLA map records",
    media: { kind: "map", url: "https://dp.la/item/example-morocco-map", accessibility: { altText: "Historic map of Morocco from a library collection" } },
    rights: { licenseId: "public-domain", sourceVerified: true, attribution: "DPLA holding institution" }
  }
]);
